[package]
name = "sandouq-fatwa"
version = "1.1.13"
description = "ط·آµط¸â€ ط·آ¯ط¸ث†ط¸â€ڑ ط·آ§ط¸â€‍ط¸ظ¾ط·ع¾ط¸ث†ط¸â€° ط¸â€¦ط·آ³ط·آ¬ط·آ¯ ط·آ§ط¸â€‍ط·آ¥ط¸ظ¹ط¸â€¦ط·آ§ط¸â€  - 150 ط¸â€¦ط·آ³ط¸ئ’ط¸â€ "
authors = ["Youcef HAMOUALI"]
edition = "2021"

[lib]
name = "sandouq_fatwa_lib"
crate-type = ["staticlib", "cdylib", "lib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
tauri-plugin-notification = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
